version: '3.8'
services:
  osrm:
    image: osrm/osrm-backend
    container_name: osrm-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: "osrm-routed --algorithm mld /data/new-york.osrm"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  backend-python:
    build: ./backend-python
    container_name: greenlink_python
    restart: always
    ports:
      - "8000:8000"

  backend-java:
    build: ./backend-java
    container_name: greenlink_java
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_CORS_ALLOWED_ORIGINS: http://44.204.109.54,http://44.204.109.54:3000,http://greenlink.website,http://www.greenlink.website,https://greenlink.website,https://www.greenlink.website
      APP_OSRM_BASE_URL: ${APP_OSRM_BASE_URL}
      APP_SOLVER_BASE_URL: ${APP_SOLVER_BASE_URL}
      JWT_SECRET: ChangeMeToA32ByteMinimumSecretKey123456
    depends_on:
      - backend-python
      - osrm

  frontend-next:
    build: ./frontend-next
    container_name: greenlink_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://44.204.109.54
    depends_on:
      - backend-java

  nginx:
    image: nginx:alpine
    container_name: greenlink_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend-next
      - backend-java
